name: weather_app
description: Simple Weather App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  colorize_lumberdash: ^3.0.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_svg: ^0.23.0+1
  freezed: ^0.15.1+1
  geocoding: ^2.0.1
  geolocator: ^7.7.1
  get_it: ^7.2.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  lumberdash: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^0.15.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
